variables:
  ACR_NAME: 'acrmicroservices1'
  IMAGE_NAME: 'user-service'
  SERVICE_CONNECTION: 'MCICD_ASC'  # Ensure the name matches exactly

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildPushImage
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(SERVICE_CONNECTION)  # Reference service connection here
        repository: $(IMAGE_NAME)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

