trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'acrmicroservices1'
  IMAGE_NAME: 'user-service'

stages:
- stage: Build
  jobs:
  - job: BuildPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(ACR_NAME)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    steps:
    - script: |
        az aks get-credentials --resource-group Microservices-CI-CD-RG --name MicroservicesAKSCluster
      displayName: 'Set AKS Credentials'
      
    - script: |
        kubectl set image deployment/user-service-deployment user-service=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
      displayName: 'Deploy to AKS'

