apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: acrmicroservices1.azurecr.io/user-service:latest
        imagePullPolicy: Always  # Force Kubernetes to always pull the latest image
        ports:
        - containerPort: 3000

